/* Supprime - Crée - Utilise la DB */
DROP DATABASE IF EXISTS papyrus;
CREATE DATABASE papyrus;
USE papyrus;

CREATE TABLE produit (
	CODART    CHAR(4) 		NOT NULL,
	LIBART    VARCHAR(30) 	NOT NULL,
	STKALE    INT NOT 		NULL,
	STKPHY    INT NOT 		NULL,
	QTEANN    INT NOT 		NULL,
	UNIMES    CHAR(5) 		NOT NULL,
	PRIMARY KEY (CODART)
);

CREATE TABLE fournis (
	NUMFOU	INT 			AUTO_INCREMENT, 
	NOMFOU	VARCHAR(25) 	NOT NULL, 
	RUEFOU	VARCHAR(50) 	NOT NULL, 
	POSFOU	CHAR(5) 		NOT NULL, 
	VILFOU	VARCHAR(30) 	NOT NULL, 
	CONFOU	VARCHAR(15) 	NOT NULL, 
	SATISF	TINYINT(3) 	CHECK (SATISF BETWEEN 1 AND 10),
	PRIMARY KEY (NUMFOU)
); 


CREATE TABLE entcom (
	
	NUMCOM    INT 				AUTO_INCREMENT,
	OBSCOM    VARCHAR(50),
	DATCOM    TIMESTAMP 		NOT NULL,
	NUMFOU    INT,
	PRIMARY KEY (NUMCOM),
	FOREIGN KEY (NUMFOU) REFERENCES fournis(NUMFOU)
);


CREATE TABLE ligcom (
	NUMLIG	INT					AUTO_INCREMENT, 
	QTECDE	INT(10) 			NOT NULL, 
	PRIUNI	DECIMAL(9,2) 		NOT NULL, 
	QTELIV	INT(10), 
	DERLIV	DATE			 	NOT NULL, 
	NUMCOM	INT 				NOT NULL, 
	CODART	CHAR(4) 			NOT NULL, 
	PRIMARY KEY (NUMLIG, NUMCOM),
	FOREIGN KEY (NUMCOM) REFERENCES entcom(NUMCOM), 
	FOREIGN KEY (CODART) REFERENCES produit(CODART)
);

/* Sur Merie on aurait 

ENTITE(produit) -- 1,N -- ASSO(vente) --  -- ENTITE(entcom)

*/
CREATE TABLE vente (
	NUMFOU 		INT 			NOT NULL,
	CODART		CHAR(4)		 	NOT NULL,
	DELLIV		INT				NOT NULL, 
	QTE1		INT 			NOT NULL, 
	PRIX1		DECIMAL(9,2) 	NOT NULL, 
	QTE2		INT, 
	PRIX2		DECIMAL(9,2), 
	QTE3		INT, 
	PRIX3		DECIMAL(9,2),
	PRIMARY KEY (NUMFOU, CODART), 
	FOREIGN KEY (NUMFOU) REFERENCES fournis(NUMFOU), 
	FOREIGN KEY (CODART) REFERENCES produit(CODART)
);